/crazyflie_server:
  ros__parameters:
    warnings:
      frequency: 1.0
      motion_capture:
        warning_if_rate_outside:
        - 80.0
        - 120.0
      communication:
        max_unicast_latency: 10.0
        min_unicast_ack_rate: 0.9
        min_unicast_receive_rate: 0.9
        min_broadcast_receive_rate: 0.9
        publish_stats: false
    firmware_params:
      query_all_values_on_connect: false
    sim:
      max_dt: 0
      backend: np
      visualizations:
        rviz:
          enabled: true
        pdf:
          enabled: false
          output_file: result.pdf
        record_states:
          enabled: false
          output_dir: state_info
          logging_time: 0.2
          file_formats:
          - csv
          - np
        blender:
          enabled: false
          fps: 1
          cycle_bg: false
          cf_cameras:
            cf231:
              calibration:
                tvec:
                - 0
                - 0
                - 0
                rvec:
                - 1.2092
                - -1.2092
                - 1.2092
            cf5:
              calibration:
                tvec:
                - 0
                - 0
                - 0
                rvec:
                - 0.61394313
                - -0.61394313
                - 1.48218982
      controller: mellinger
    robots:
      cf21:
        enabled: true
        uri: radio://0/90/2M/E7E7E7E7E6
        initial_position:
        - 0.0
        - 0.0
        - 0.0
        type: cf21
        firmware_logging:
          enabled: true
          verbosity: 1
          default_topics:
            pose:
              frequency: 5
          custom_topics:
            OptimizationPosition:
              frequency: 5
              vars:
              - Optimization_Model.T_x
              - Optimization_Model.T_y
              - Optimization_Model.T_z
            MyKalmanPosition:
              frequency: 5
              vars:
              - Optimization_Model.KF_x
              - Optimization_Model.KF_y
              - Optimization_Model.KF_z
            VoltagesCalibrated:
              frequency: 5
              vars:
              - Dipole_Model.M_V1
              - Dipole_Model.M_V2
              - Dipole_Model.M_V3
              - Dipole_Model.M_V4
            Outliers_distances:
              frequency: 5
              vars:
              - Optimization_Model.Out_d
              - Optimization_Model.Out_z
            ZRange:
              frequency: 5
              vars:
              - range.zrange
    robot_types:
      cf21:
        motion_capture:
          enabled: false
        big_quad: false
        battery:
          voltage_warning: 3.2
          voltage_critical: 3.0
        firmware_logging:
          enabled: true
    all:
      firmware_params:
        commander:
          enHighLevel: 1
        stabilizer:
          estimator: 2
          controller: 1
      broadcasts:
        num_repeats: 15
        delay_between_repeats_ms: 1
    robot_description: "<?xml version=\"1.0\"?>\n<robot name=\"$NAME\">\n  <link name=\"\
      $NAME\">\n    <origin rpy=\"0 0 0\" xyz=\"0.0 0 0\" />\n    <visual>\n     \
      \   <geometry>\n          <mesh filename=\"package://crazyflie/urdf/cf2_assembly_with_props.dae\"\
      \ scale=\"1.0 1.0 1.0\"/>\n        </geometry>\n    </visual>\n  </link>\n</robot>"
    poses_qos_deadline: 100.0
